<?php

/**
 * This is the model base class for the table "game_to_collection".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "GameToCollection".
 *
 * Columns in table "game_to_collection" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $game_id
 * @property integer $collection_id
 *
 */
abstract class BaseGameToCollection_ extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'game_to_collection';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'GameToCollection|GameToCollections', $n);
	}

	public static function representingColumn() {
		return array(
			'game_id',
			'collection_id',
		);
	}

	public function rules() {
		return array(
			array('game_id, collection_id', 'required'),
			array('game_id, collection_id', 'numerical', 'integerOnly'=>true),
			array('game_id, collection_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'game_id' => null,
			'collection_id' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('game_id', $this->game_id);
		$criteria->compare('collection_id', $this->collection_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
			'pagination'=>array(
        'pageSize'=>Yii::app()->fbvStorage->get("settings.pagination_size"),
      ),
		));
	}
}