<?php

/**
 * This is the model base class for the table "played_game".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PlayedGame".
 *
 * Columns in table "played_game" available as properties of the model,
 * followed by relations of table "played_game" available as properties of the model.
 *
 * @property integer $id
 * @property integer $session_id
 * @property integer $game_id
 * @property integer $score
 * @property string $created
 * @property string $modified
 * @property string $finished
 *
 * @property GameSubmission[] $gameSubmissions
 * @property Game $game
 * @property Session $session
 */
abstract class BasePlayedGame extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'played_game';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PlayedGame|PlayedGames', $n);
	}

	public static function representingColumn() {
		return 'created';
	}

	public function rules() {
		return array(
			array('session_id, game_id, created, modified', 'required'),
			array('session_id, game_id, score', 'numerical', 'integerOnly'=>true),
			array('finished', 'safe'),
			array('score, finished', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, session_id, game_id, score, created, modified, finished', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'gameSubmissions' => array(self::HAS_MANY, 'GameSubmission', 'played_game_id'),
			'game' => array(self::BELONGS_TO, 'Game', 'game_id'),
			'session' => array(self::BELONGS_TO, 'Session', 'session_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'session_id' => null,
			'game_id' => null,
			'score' => Yii::t('app', 'Score'),
			'created' => Yii::t('app', 'Created'),
			'modified' => Yii::t('app', 'Modified'),
			'finished' => Yii::t('app', 'Finished'),
			'gameSubmissions' => null,
			'game' => null,
			'session' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('session_id', $this->session_id);
		$criteria->compare('game_id', $this->game_id);
		$criteria->compare('score', $this->score);
		$criteria->compare('created', $this->created, true);
		$criteria->compare('modified', $this->modified, true);
		$criteria->compare('finished', $this->finished, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
			'pagination'=>array(
        'pageSize'=>Yii::app()->params['pagination.pageSize'],
      ),
		));
	}
}