<?php

/**
 * This is the model base class for the table "image".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Image".
 *
 * Columns in table "image" available as properties of the model,
 * followed by relations of table "image" available as properties of the model.
 *
 * @property integer $id
 * @property string $file
 * @property string $created
 * @property string $modified
 * @property string $last_access
 *
 * @property ImageSet[] $imageSets
 * @property TagUse[] $tagUses
 */
abstract class BaseImage extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'image';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Image|Images', $n);
	}

	public static function representingColumn() {
		return 'file';
	}

	public function rules() {
		return array(
			array('file, created, modified', 'required'),
			array('file', 'length', 'max'=>254),
			array('last_access', 'safe'),
			array('last_access', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, file, created, modified, last_access', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'imageSets' => array(self::MANY_MANY, 'ImageSet', 'image_set_to_image(image_id, image_set_id)'),
			'tagUses' => array(self::HAS_MANY, 'TagUse', 'image_id'),
		);
	}

	public function pivotModels() {
		return array(
			'imageSets' => 'ImageSetToImage',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'file' => Yii::t('app', 'File'),
			'created' => Yii::t('app', 'Created'),
			'modified' => Yii::t('app', 'Modified'),
			'last_access' => Yii::t('app', 'Last Access'),
			'imageSets' => null,
			'tagUses' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('file', $this->file, true);
		$criteria->compare('created', $this->created, true);
		$criteria->compare('modified', $this->modified, true);
		$criteria->compare('last_access', $this->last_access, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
			'pagination'=>array(
        'pageSize'=>Yii::app()->params['pagination.pageSize'],
      ),
		));
	}
}