<?php

/**
 * This is the model base class for the table "image_set_to_subject_matter".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ImageSetToSubjectMatter".
 *
 * Columns in table "image_set_to_subject_matter" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $image_set_id
 * @property integer $subject_matter_id
 *
 */
abstract class BaseImageSetToSubjectMatter extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'image_set_to_subject_matter';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ImageSetToSubjectMatter|ImageSetToSubjectMatters', $n);
	}

	public static function representingColumn() {
		return array(
			'image_set_id',
			'subject_matter_id',
		);
	}

	public function rules() {
		return array(
			array('image_set_id, subject_matter_id', 'required'),
			array('image_set_id, subject_matter_id', 'numerical', 'integerOnly'=>true),
			array('image_set_id, subject_matter_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'image_set_id' => null,
			'subject_matter_id' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('image_set_id', $this->image_set_id);
		$criteria->compare('subject_matter_id', $this->subject_matter_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
			'pagination'=>array(
        'pageSize'=>Yii::app()->params['pagination.pageSize'],
      ),
		));
	}
}