<?php

/**
 * This is the model base class for the table "blocked_ip".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "BlockedIp".
 *
 * Columns in table "blocked_ip" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $ip
 * @property string $type
 * @property string $created
 * @property string $modified
 *
 */
abstract class BaseBlockedIp extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'blocked_ip';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'BlockedIp|BlockedIps', $n);
	}

	public static function representingColumn() {
		return 'ip';
	}

	public function rules() {
		return array(
			array('ip, created, modified', 'required'),
			array('ip', 'length', 'max'=>45),
			array('type', 'length', 'max'=>5),
			array('type', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, ip, type, created, modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'ip' => Yii::t('app', 'Ip'),
			'type' => Yii::t('app', 'Type'),
			'created' => Yii::t('app', 'Created'),
			'modified' => Yii::t('app', 'Modified'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('ip', $this->ip, true);
		$criteria->compare('type', $this->type, true);
		$criteria->compare('created', $this->created, true);
		$criteria->compare('modified', $this->modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
			'pagination'=>array(
        'pageSize'=>Yii::app()->fbvStorage->get("settings.pagination_size"),
      ),
		));
	}
}