<?php

/**
 * This is the model base class for the table "game_partner".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "GamePartner".
 *
 * Columns in table "game_partner" available as properties of the model,
 * followed by relations of table "game_partner" available as properties of the model.
 *
 * @property integer $id
 * @property integer $session_id_1
 * @property integer $session_id_2
 * @property integer $game_id
 * @property string $created
 * @property integer $played_game_id
 *
 * @property Game $game
 * @property PlayedGame $playedGame
 * @property Session $sessionId1
 * @property Session $sessionId2
 */
abstract class BaseGamePartner_ extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'game_partner';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'GamePartner|GamePartners', $n);
	}

	public static function representingColumn() {
		return 'created';
	}

	public function rules() {
		return array(
			array('session_id_1, game_id, created', 'required'),
			array('session_id_1, session_id_2, game_id, played_game_id', 'numerical', 'integerOnly'=>true),
			array('session_id_2, played_game_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, session_id_1, session_id_2, game_id, created, played_game_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'game' => array(self::BELONGS_TO, 'Game', 'game_id'),
			'playedGame' => array(self::BELONGS_TO, 'PlayedGame', 'played_game_id'),
			'sessionId1' => array(self::BELONGS_TO, 'Session', 'session_id_1'),
			'sessionId2' => array(self::BELONGS_TO, 'Session', 'session_id_2'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'session_id_1' => null,
			'session_id_2' => null,
			'game_id' => null,
			'created' => Yii::t('app', 'Created'),
			'played_game_id' => null,
			'game' => null,
			'playedGame' => null,
			'sessionId1' => null,
			'sessionId2' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('session_id_1', $this->session_id_1);
		$criteria->compare('session_id_2', $this->session_id_2);
		$criteria->compare('game_id', $this->game_id);
		$criteria->compare('created', $this->created, true);
		$criteria->compare('played_game_id', $this->played_game_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
			'pagination'=>array(
        'pageSize'=>Yii::app()->fbvStorage->get("settings.pagination_size"),
      ),
		));
	}
}