<?php

/**
 * This is the model base class for the table "game_to_image_set".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "GameToImageSet".
 *
 * Columns in table "game_to_image_set" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $game_id
 * @property integer $image_set_id
 *
 */
abstract class BaseGameToImageSet extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'game_to_image_set';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'GameToImageSet|GameToImageSets', $n);
	}

	public static function representingColumn() {
		return array(
			'game_id',
			'image_set_id',
		);
	}

	public function rules() {
		return array(
			array('game_id, image_set_id', 'required'),
			array('game_id, image_set_id', 'numerical', 'integerOnly'=>true),
			array('game_id, image_set_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'game_id' => null,
			'image_set_id' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('game_id', $this->game_id);
		$criteria->compare('image_set_id', $this->image_set_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
			'pagination'=>array(
        'pageSize'=>Yii::app()->params['pagination.pageSize'],
      ),
		));
	}
}